# Generated by Django 3.0.6 on 2020-05-25 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0003_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 25, 6, 56, 20, 318128, tzinfo=utc))),
                ('customer', models.ManyToManyField(to='fullstack.CustomerProfile')),
                ('service_provider', models.ManyToManyField(to='fullstack.ServiceProvider')),
            ],
        ),
    ]
