# Generated by Django 3.0.6 on 2020-05-25 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 8, 2, 35, 544820, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspension_start_date', models.DateTimeField(default=datetime.datetime(2020, 5, 25, 8, 2, 35, 546821, tzinfo=utc))),
                ('suspension_end_date', models.DateTimeField(default=datetime.datetime(2020, 5, 25, 8, 2, 35, 546821, tzinfo=utc))),
                ('suspension_reason', models.CharField(max_length=100)),
                ('offense_discription', models.TextField()),
                ('service_provider', models.ManyToManyField(to='fullstack.ServiceProvider')),
            ],
        ),
    ]
