# Generated by Django 3.0.6 on 2020-06-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0005_auto_20200603_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='supporting_document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
