# Generated by Django 3.0.6 on 2020-05-25 08:03

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0005_auto_20200525_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 8, 3, 23, 578872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='suspension_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='suspension_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
