# Generated by Django 3.0.6 on 2020-05-25 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0006_auto_20200525_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 8, 4, 34, 310254, tzinfo=utc)),
        ),
    ]
