# Generated by Django 3.0.6 on 2020-06-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0007_serviceprovider_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='document_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fullstack.Document'),
            preserve_default=False,
        ),
    ]
