# Generated by Django 3.0.6 on 2020-05-25 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0007_auto_20200525_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
