# Generated by Django 3.0.6 on 2020-05-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0008_auto_20200525_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fullstack.CustomerProfile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fullstack.ServiceProvider'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='suspension',
            name='service_provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fullstack.ServiceProvider'),
            preserve_default=False,
        ),
    ]
