# Generated by Django 3.0.6 on 2020-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
