# Generated by Django 3.0.6 on 2020-06-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('fullstack', '0002_auto_20200622_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('city_ascii', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=50)),
                ('iso2', models.CharField(max_length=10)),
                ('iso3', models.CharField(max_length=10)),
                ('admin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
