# Generated by Django 3.0.6 on 2020-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0002_auto_20200603_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='picture',
            field=models.ImageField(blank=True, default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
