# Generated by Django 3.0.6 on 2020-06-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0003_auto_20200624_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.MyCity'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.MyCity'),
        ),
    ]
