# Generated by Django 3.0.6 on 2020-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0004_auto_20200624_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycity',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mycity',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mycity',
            name='city_ascii',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mycity',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mycity',
            name='iso2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mycity',
            name='iso3',
            field=models.CharField(max_length=50),
        ),
    ]
