# Generated by Django 3.0.6 on 2020-06-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0010_auto_20200604_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAndReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Excellent', 'Excellent')], default=('Good', 'Good'), max_length=50)),
                ('reviews', models.TextField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.CustomerProfile')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.ServiceProvider')),
            ],
        ),
    ]
