# Generated by Django 3.0.6 on 2020-06-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0011_ratingandreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingandreview',
            old_name='reviews',
            new_name='review',
        ),
    ]
