# Generated by Django 3.0.6 on 2020-06-06 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0012_auto_20200606_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingandreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
